language: python
python:
- "3.6"

jobs:
  include:
    - stage: test
      before_script:
      - pip install -r requirements.txt
      - sudo apt-get update
      - sudo apt-get install -y spatialite-bin libspatialite5
      script:
      - python build_cryptids_database.py
    - stage: deploy cryptids.datasettes.com
      if: branch = master AND type = push
      before_script:
      - pip install -r requirements.txt
      - sudo apt-get update
      - sudo apt-get install -y spatialite-bin libspatialite5
      - pip install datasette
      - npm install -g now
      script:
      - python build_cryptids_database.py
      after_success:
      - datasette publish now cryptids.db --spatialite -m metadata.json --template-dir=templates --token=$NOW_TOKEN --name=cryptids --install=datasette-leaflet-geojson
      - now alias --token=$NOW_TOKEN
